### ISSUE TITLE
Retrain old models with robustness fixes

### ISSUE THREAD

**Issue by gregtatum** [mozilla/translations#757] opened 2024-07-19 17:55 UTC
We will need to retrain models that don't have the robustness fixes from using OpusTrainer. 
- [ ] bg-en
- [ ] de-en
- [ ] en-bg
- [ ] en-de
- [ ] en-es
- [ ] en-et
- [ ] en-fa
- [ ] en-fr
- [ ] en-it
- [ ] en-nl
- [ ] en-pl
- [ ] en-pt
- [ ] en-sl
- [ ] en-tr
- [ ] es-en
- [ ] et-en
- [ ] fa-en
- [ ] fi-en
- [ ] fr-en
- [ ] hu-en
- [ ] is-en
- [ ] it-en
- [ ] mt-en
- [ ] nb-en
- [ ] nn-en
- [ ] nl-en
- [ ] pl-en
- [ ] pt-en
- [ ] tr-en

**Comment by gregtatum** [comment] 2024-07-19 18:31
Verify the fix with:

https://bugzilla.mozilla.org/show_bug.cgi?id=1888970
https://bugzilla.mozilla.org/show_bug.cgi?id=1888897
https://bugzilla.mozilla.org/show_bug.cgi?id=1884577
https://bugzilla.mozilla.org/show_bug.cgi?id=1881252
https://bugzilla.mozilla.org/show_bug.cgi?id=1864472
https://bugzilla.mozilla.org/show_bug.cgi?id=1862486

**Comment by marco-c** [comment] 2024-11-14 17:42
Closing as duplicate of #891.

**Closed by marco-c** 2024-11-14 17:41 UTC
Labels: quality
